name: publish
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  tests-win:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: napi build
        run: yarn install && yarn build
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-napi
          path: ./*.node
          if-no-files-found: error
  build:
    runs-on: ubuntu-latest
    needs:
      - tests-win
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: pull artifacts
        uses: actions/download-artifact@v3
        with:
          name: windows-napi
      - name: install deps
        run: yarn install
      - name: check changefiles
        run: yarn check-changefile
      - name: build
        run: yarn build
      - name: prep
        run: |
          mkdir artifacts
          cp *.node artifacts
          yarn artifacts
      - name: publish
        run: |
          git config --global user.email "edgar21_9@hotmail.com"
          git config --global user.name "Edgar"
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          # yarn prepublishOnly
          yarn beachball publish -c .beachball.js -y --token $NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}      
